# Generated by Django 5.1.3 on 2024-12-09 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_alter_user_department'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Full_name', models.CharField(max_length=20, null=True)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('message', models.CharField(max_length=120, null=True)),
                ('created_at', models.DateField()),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='grade',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='tax_code',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
