# Generated by Django 5.1.3 on 2024-12-09 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_contact_user_grade_user_tax_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='created_at',
        ),
    ]
