# Generated by Django 5.1.3 on 2024-12-02 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_remove_product_category_product_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='contact',
        ),
        migrations.AddField(
            model_name='product',
            name='content',
            field=models.TextField(blank=True, null=True, verbose_name='Product Discription'),
        ),
    ]
