# Generated by Django 5.1.3 on 2024-12-12 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_remove_product_contact_product_content'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'permissions': [('can_change_category', 'Can change category')]},
        ),
    ]
